"""shinystatic CLI — Shiny Express .qmd → static .qmd / standalone Express app."""

import argparse
import json
import subprocess
import sys
from pathlib import Path

from shinystatic._version import __version__
from shinystatic.core import (
    convert_static,
    generate_express,
    write_templates,
)

EXAMPLES = """\
examples:
  shinystatic --init                           Write Typst templates locally
  shinystatic doc.qmd --mode express            Generate standalone Express app
  shinystatic doc.qmd --mode static --render    Convert + render PDF
  shinystatic doc.qmd --params p.json --render  Use exported parameters
"""


def _log(msg: str) -> None:
    """Write progress messages to stderr so stdout stays machine-parseable."""
    print(msg, file=sys.stderr)


def _fail(msg: str, exit_code: int = 1) -> None:
    _log(f"Error: {msg}")
    sys.exit(exit_code)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="shinystatic — Shiny Express .qmd → static .qmd / standalone Express app",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=EXAMPLES,
    )
    parser.add_argument("source", nargs="?", help="Source .qmd file (omit with --init)")
    parser.add_argument("--mode", choices=["express", "static"], default="static",
                        help="express: generate standalone app | static: generate static .qmd (default)")
    parser.add_argument("--params", metavar="JSON", help="params.json (Shiny exported parameters)")
    parser.add_argument("--render", action="store_true",
                        help="(static mode) run quarto render --to typst after conversion")
    parser.add_argument("--init", action="store_true",
                        help="Write Typst template files to current directory")
    parser.add_argument("-o", "--output", metavar="PATH", help="Output file path")
    parser.add_argument("--version", action="version", version=f"shinystatic {__version__}")
    args = parser.parse_args()

    if args.init:
        write_templates(".")
        _log("Written: typst-preamble.typ, typst-cover.typ")
        _log("Next: run 'shinystatic doc.qmd --mode static --render' to convert + build PDF")
        return

    if not args.source:
        parser.error("source argument is required (or use --init to write templates)")

    source_path = Path(args.source)
    if not source_path.exists():
        _fail(f"file not found: '{args.source}'. Check the path and try again.")

    try:
        source_text = source_path.read_text(encoding="utf-8")
    except OSError as e:
        _fail(f"cannot read '{args.source}': {e}")

    if args.mode == "express":
        output = args.output or source_path.stem + "_express.py"
        _log(f"Express: {args.source} → {output}")
        try:
            Path(output).write_text(generate_express(source_text), encoding="utf-8")
        except OSError as e:
            _fail(f"cannot write '{output}': {e}")
        _log(f"Done: {output} -> run with 'shiny run {output}'")
        return

    # static mode
    params = None
    if args.params:
        params_path = Path(args.params)
        if not params_path.exists():
            _fail(f"params file not found: '{args.params}'")
        try:
            params = json.loads(params_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            _fail(f"invalid params file '{args.params}': {e}")

    output = args.output or source_path.stem + "-static.qmd"
    _log(f"Convert: {args.source} → {output}")
    try:
        result, meta = convert_static(source_text, params)
        Path(output).write_text(result, encoding="utf-8")
    except ValueError as e:
        _fail(str(e))
    except OSError as e:
        _fail(f"cannot write '{output}': {e}")
    _log(f"Done: {output}")

    out_dir = str(Path(output).parent) or "."
    write_templates(out_dir, meta)

    if params:
        yml_path = Path(output).stem + "-params.yml"
        lines = ["# Parameter overrides — generated by shinystatic", ""]
        for k, v in params.items():
            if isinstance(v, str):
                lines.append(f'{k}: "{v}"')
            elif isinstance(v, list):
                lines.append(f"{k}: {v}")
            elif isinstance(v, bool):
                lines.append(f"{k}: {str(v).lower()}")
            else:
                lines.append(f"{k}: {v}")
        Path(yml_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
        _log(f"Params: {yml_path}")

    if args.render:
        cmd = ["quarto", "render", output, "--to", "typst"]
        if params:
            cmd += ["--execute-params", yml_path]
        _log(f"Render: {' '.join(cmd)}")
        subprocess.run(cmd, check=False)


if __name__ == "__main__":
    main()
