"""Core conversion logic — content-agnostic transformer for Shiny Express .qmd files."""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any

# ═══════════════════════════════════════════════
# Embedded Typst templates
# ═══════════════════════════════════════════════

TYPST_PREAMBLE = r"""// Page setup
#set page(
  paper: "a4",
  margin: (top: 2.8cm, bottom: 2.2cm, left: 3.0cm, right: 2.5cm),
  numbering: "1",
  number-align: center,
)

// Body text
#set par(leading: 0.65em, first-line-indent: 2em, justify: true)
#set text(font: "Noto Sans CJK SC", size: 10.5pt, lang: "zh")

// Headings
#set heading(numbering: "1.1")
#show heading.where(level: 1): it => {
  set text(size: 15pt, weight: "bold"); set par(leading: 0.8em)
  v(0.6em); it; v(0.3em)
}
#show heading.where(level: 2): it => {
  set text(size: 12.5pt, weight: "bold"); set par(leading: 0.7em)
  v(0.4em); it; v(0.2em)
}

// Tables
#show table: it => {
  set table(inset: (x: 6pt, y: 3pt), align: center + horizon)
  it
}

// Figures
#show figure: it => {
  set text(size: 9pt, fill: rgb("555555"))
  it
}
"""

TYPST_COVER = r"""// Cover page (generated by shinystatic)
#set align(center)
#set par(first-line-indent: 0em)
#v(4cm)
#set text(size: 24pt, weight: "bold")
[{title}]

#v(1.2cm)
#set text(size: 14pt, weight: "regular")
[{subtitle}]

#v(3cm)
#set text(size: 11pt, weight: "regular")
#table(
  columns: (auto, auto),
  inset: 10pt,
  align: (right, left),
  [Prepared by:], [{author}],
  [Date:], [{date}],
)

#v(1cm)
#set text(size: 9pt, fill: gray)
[Confidential — For Internal Use Only]

#pagebreak()
"""


def write_templates(out_dir: str, meta: dict[str, str] | None = None) -> None:
    """Write Typst template files to out_dir, injecting document metadata into the cover."""
    if meta is None:
        meta = {}
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    (d / "typst-preamble.typ").write_text(TYPST_PREAMBLE)
    cover = TYPST_COVER.format(
        title=meta.get("title", "Untitled"),
        subtitle=meta.get("subtitle", ""),
        author=meta.get("author", ""),
        date=meta.get("date", "today"),
    )
    (d / "typst-cover.typ").write_text(cover)


# ═══════════════════════════════════════════════
# Utilities
# ═══════════════════════════════════════════════

SPLIT_RE = re.compile(r"(```\{python\}.*?```)", re.DOTALL)
LABEL_RE = re.compile(r'#\|\s*label:\s*(\S+)')


def parse_cells(source: str) -> list[dict[str, Any]]:
    """Parse .qmd body into a list of {type, label, code} dicts."""
    cells: list[dict[str, Any]] = []
    for part in SPLIT_RE.split(source):
        if part.startswith("```{python}"):
            code = part[len("```{python}"):]
            if code.endswith("```"):
                code = code[:-3]
            code = code.strip()
            m = LABEL_RE.search(code)
            cells.append({"type": "python", "label": m.group(1) if m else None, "code": code})
        elif part.strip():
            cells.append({"type": "markdown", "label": None, "code": part})
    return cells


# ═══════════════════════════════════════════════
# YAML
# ═══════════════════════════════════════════════

def parse_yaml(source: str) -> tuple[dict[str, str], str]:
    """Return (metadata dict, body without YAML front matter)."""
    m = re.match(r'^---\n(.*?)\n---\n', source, re.DOTALL)
    if not m:
        return {}, source
    meta: dict[str, str] = {}
    for line in m.group(1).split("\n"):
        kv = re.match(r'^(\w[\w_-]*):\s*(.*)', line)
        if kv:
            meta[kv.group(1)] = kv.group(2).strip().strip('"').strip("'")
    return meta, source[m.end():]


def build_static_yaml(meta: dict[str, str]) -> str:
    """Generate static-document YAML header from source metadata."""
    title = meta.get("title", "Untitled")
    subtitle = meta.get("subtitle", "")
    author = meta.get("author", "")
    date = meta.get("date", "today")
    lang = meta.get("lang", "zh")
    return "\n".join([
        "---",
        f'title: "{title}"',
        f'subtitle: "{subtitle}"',
        f'author: "{author}"',
        f"date: {date}",
        f"lang: {lang}",
        "format:",
        "  typst:",
        "    toc: true",
        "    toc-depth: 2",
        "    number-sections: true",
        "    include-in-header: typst-preamble.typ",
        "    include-before-body: typst-cover.typ",
        "execute:",
        "  echo: false",
        "  warning: false",
        "  message: false",
        "---",
    ]) + "\n"


# ═══════════════════════════════════════════════
# DEFAULTS extraction
# ═══════════════════════════════════════════════

def extract_defaults(cells: list[dict[str, Any]]) -> dict[str, Any]:
    """Extract the DEFAULTS dict literal from params-* or setup cells."""
    for cell in cells:
        if cell.get("type") != "python":
            continue
        label = cell.get("label", "")
        if label and (label.startswith("params-") or label == "setup"):
            m = re.search(r'(\w+)\s*=\s*\{', cell["code"])
            if m:
                key = m.group(1)
                try:
                    tree = ast.parse(cell["code"])
                    for node in ast.walk(tree):
                        if isinstance(node, ast.Assign):
                            for target in node.targets:
                                if isinstance(target, ast.Name) and target.id == key:
                                    val = ast.literal_eval(node.value)
                                    if isinstance(val, dict):
                                        return val
                except (SyntaxError, ValueError):
                    pass
    return {}


def generate_parameters_cell(defaults: dict[str, Any]) -> str:
    """Generate a Papermill-compatible parameters cell from a defaults dict."""
    lines = [
        "```{python}",
        "#| label: parameters",
        "#| tags: [parameters]",
        "import numpy as np",
        "import pandas as pd",
        "import matplotlib.pyplot as plt",
        "import matplotlib as mpl",
        "",
        'mpl.rcParams["font.sans-serif"] = ["Noto Sans CJK SC", "Microsoft YaHei", "SimHei"]',
        'mpl.rcParams["axes.unicode_minus"] = False',
        'mpl.rcParams["figure.dpi"] = 110',
        "",
    ]
    for k, v in defaults.items():
        if isinstance(v, str):
            lines.append(f'{k} = "{v}"')
        elif isinstance(v, list):
            lines.append(f"{k} = {v}")
        elif isinstance(v, float):
            lines.append(f"{k} = {v}")
        elif isinstance(v, bool):
            lines.append(f"{k} = {str(v).lower()}")
        else:
            lines.append(f"{k} = {v}")
    lines.append("```")
    return "\n".join(lines) + "\n"


# ═══════════════════════════════════════════════
# Model detection
# ═══════════════════════════════════════════════

def detect_model_module(cells: list[dict[str, Any]]) -> tuple[str, str] | None:
    """Detect (module_alias, function_name) from the model-* cell, e.g. ('mlib', 'compute')."""
    for cell in cells:
        if cell.get("type") != "python":
            continue
        label = cell.get("label", "")
        if label and label.startswith("model-"):
            code = cell["code"]
            # from X import Y as Z
            from_imports = re.findall(r'from\s+(\S+)\s+import\s+(\w+)\s+as\s+(\w+)', code)
            for _module_path, _obj, alias in from_imports:
                m = re.search(rf'return\s+{alias}\.(\w+)\(', code)
                if m:
                    return alias, m.group(1)
            # import X as Y
            imports = re.findall(r'import\s+(\w+)\s+as\s+(\w+)', code)
            for _mod, alias in imports:
                m = re.search(rf'return\s+{alias}\.(\w+)\(', code)
                if m:
                    return alias, m.group(1)
            # return mod.func()
            m = re.search(r'return\s+(\w+)\.(\w+)\(', code)
            if m:
                return m.group(1), m.group(2)
    return None


def generate_model_cell(module_name: str, func_name: str) -> str:
    """Generate the static model computation cell."""
    return f"""```{{python}}
#| label: model-static
_params = {{k: v for k, v in locals().items() if not k.startswith("_")}}
m = {module_name}.{func_name}(_params)
```
"""


# ═══════════════════════════════════════════════
# Import detection
# ═══════════════════════════════════════════════

def detect_imports(cells: list[dict[str, Any]]) -> str:
    """Extract non-Shiny import statements and mpl config from the setup cell."""
    lines = []
    for cell in cells:
        if cell.get("type") != "python":
            continue
        if cell.get("label") == "setup":
            for line in cell["code"].split("\n"):
                s = line.strip()
                if "shiny" in s:
                    continue
                if s.startswith("import ") or s.startswith("from "):
                    lines.append(line)
                elif "mpl.rcParams" in s or "mpl.rc" in s:
                    lines.append(line)
            break
    return "\n".join(lines)


def generate_setup_cell(imports: str) -> str:
    """Generate the static setup cell (imports + mpl config)."""
    has_rc = "mpl.rcParams" in imports
    extra = "" if has_rc else (
        'mpl.rcParams["font.sans-serif"] = ["Noto Sans CJK SC", "Microsoft YaHei", "SimHei"]\n'
        'mpl.rcParams["axes.unicode_minus"] = False\n'
        'mpl.rcParams["figure.dpi"] = 110\n'
    )
    return f"```{{python}}\n#| label: setup-static\n{imports}\n{extra}```\n"


# ═══════════════════════════════════════════════
# Cell converters
# ═══════════════════════════════════════════════

def _extract_fstring(code: str) -> str | None:
    m = re.search(r'ui\.markdown\(f"""(.+?)"""\)', code, re.DOTALL)
    if m:
        return m.group(1)
    m = re.search(r"ui\.markdown\(f'''(.+?)'''\)", code, re.DOTALL)
    return m.group(1) if m else None


def _extract_locals(code: str) -> dict[str, str]:
    mapping: dict[str, str] = {}
    pos = code.find("return ui.markdown")
    if pos < 0:
        pos = code.find("return")
    if pos < 0:
        return mapping
    for m in re.finditer(r'^(\s*)(\w+)\s*=\s*(.+?)$', code[:pos], re.MULTILINE):
        name, val = m.group(2), m.group(3).strip().rstrip(";")
        if name != "m":
            mapping[name] = val
    return mapping


def convert_text_cell(code: str) -> str:
    """Convert a text-* cell to Markdown with {python} inline expressions."""
    body = _extract_fstring(code)
    if body is None:
        return ""

    # Expand local variables
    for name, expr in _extract_locals(code).items():
        body = re.sub(r'(?<![\w])' + re.escape(f"{{{name}}}"), f"{{{expr}}}", body)
        body = re.sub(r'(?<![\w])' + re.escape(f"{{{name}:"), f"{{{expr}:", body)

    body = body.replace("\\n", "\n")

    def _repl(m: re.Match[str]) -> str:
        expr = m.group(1)
        if ":" in expr:
            return f'`{{{{python}}}} f"{{{expr}}}"`'
        return f"`{{{{python}}}} {expr}`"

    body = re.sub(r"\{([^}]+)\}", _repl, body)
    body = body.replace("{{python}}", "{python}")
    return body.strip() + "\n"


def convert_fig_cell(code: str) -> str:
    """Convert a fig-* cell to a static plt.show() cell."""
    m = re.search(r"def \w+\(\):\s*\n(.+)", code, re.DOTALL)
    if not m:
        return ""
    body = m.group(1).strip()
    body = "\n".join(line[4:] if line.startswith("    ") else line for line in body.split("\n"))
    body = re.sub(r"return\s+", "", body).replace("model()", "m").rstrip()
    if "plt.show()" not in body:
        body += "\nplt.show()"
    return f'```{{python}}\n#| fig-cap: "Figure"\n{body}\n```\n'


def convert_tbl_cell(code: str) -> str:
    """Convert a tbl-* cell to a plain DataFrame display."""
    code = re.sub(r'@render\.data_frame(\(.*?\))?\s*\n', '', code)
    code = re.sub(r'def \w+\(\):\s*\n', '', code)
    code = "\n".join(line[4:] if line.startswith("    ") else line for line in code.split("\n"))
    code = code.replace("model()", "m")
    code = re.sub(r'\breturn\s+', '', code)
    return f"```{{python}}\n{code.strip()}\n```\n"


# ═══════════════════════════════════════════════
# Main conversion
# ═══════════════════════════════════════════════

def _drop_last_section(parts: list[str]) -> None:
    for i in range(len(parts) - 1, -1, -1):
        p = parts[i].strip()
        if p and not p.startswith("```"):
            parts[i] = ""
            return


def convert_static(source: str, params: dict[str, Any] | None = None) -> tuple[str, dict[str, str]]:
    """Convert a Shiny Express .qmd source to a static .qmd, returning (content, metadata)."""
    meta, body_source = parse_yaml(source)
    defaults = params or {}
    if not defaults:
        defaults = extract_defaults(parse_cells(body_source))
    cells = parse_cells(body_source)
    info = detect_model_module(cells)
    if not info:
        raise ValueError("No model-* cell found — cannot determine model module/function")

    imports_raw = detect_imports(cells)
    imports_lines = []
    seen = set()
    for ln in imports_raw.split("\n"):
        s = ln.strip()
        if s and s not in seen:
            imports_lines.append(ln)
            seen.add(s)

    head = [build_static_yaml(meta), "\n\n"]
    params_cell = generate_parameters_cell(defaults) + "\n"
    setup_cell = generate_setup_cell("\n".join(imports_lines)) + "\n"
    model_cell = generate_model_cell(*info) + "\n"
    body: list[str] = []

    for cell in cells:
        label = cell.get("label")
        code = cell.get("code", "")
        if cell.get("type") == "markdown":
            body.append(code + "\n\n")
            continue
        if label is None:
            if any(kw in code for kw in ("shiny", "DEFAULTS", "@reactive")):
                continue
            body.append(f"```{{python}}\n{code}\n```\n\n")
            continue
        if label.startswith("params-") or label == "setup" or label.startswith("model-"):
            continue
        if label.startswith("ui-") or label.startswith("export-"):
            _drop_last_section(body)
            continue
        if label.startswith("text-"):
            body.append(convert_text_cell(code) + "\n")
        elif label.startswith("fig-"):
            body.append(convert_fig_cell(code) + "\n")
        elif label.startswith("tbl-"):
            body.append(convert_tbl_cell(code) + "\n")
        else:
            body.append(f"```{{python}}\n{code}\n```\n\n")

    return "".join(head + [params_cell, "\n", setup_cell, "\n", model_cell, "\n"] + body), meta


# ═══════════════════════════════════════════════
# Express app generation
# ═══════════════════════════════════════════════

EXPRESS_HEADER = '''"""Shiny Express app (generated by shinystatic)"""
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from shiny import reactive
from shiny.express import input, render, ui
'''


def generate_express(source: str) -> str:
    """Generate a standalone Shiny Express app from .qmd source."""
    _, body_source = parse_yaml(source)
    cells = parse_cells(body_source)
    imports = detect_imports(cells)

    parts = [EXPRESS_HEADER, imports, "\n\n"]
    parts.append('mpl.rcParams["font.sans-serif"] = ["Noto Sans CJK SC", "Microsoft YaHei", "SimHei"]\n')
    parts.append('mpl.rcParams["axes.unicode_minus"] = False\n')
    parts.append('mpl.rcParams["figure.dpi"] = 110\n')

    for cell in cells:
        if cell.get("type") == "python" and cell.get("label", "").startswith("params-"):
            parts.append(f"\n{cell['code']}\n")
            break

    seen_labels = set()
    for cell in cells:
        if cell.get("type") != "python":
            continue
        label = cell.get("label")
        if label in seen_labels:
            continue
        seen_labels.add(label)
        if label is None:
            if "shiny" not in cell["code"] and "mpl.rc" not in cell["code"]:
                parts.append(f"\n{cell['code']}\n")
        elif label.startswith(("model-", "text-", "fig-", "tbl-", "ui-", "export-")):
            parts.append(f"\n{cell['code']}\n")

    return "".join(parts)
